apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  ports:
    - name: {{ .Values.app.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.app.name }}
  type: ClusterIP
